/*! # PSAS Telemetry

Utilities to read and write binary messages in the PSAS rocket framework.
*/

extern crate byteorder;

// This module is entirely generated by the code generator based on defined
// message types.
pub mod messages;
